#! /bin/bash
# This script is meant to evoke the algorithm without requiring any input arguments
#

# Define directory names and containers
FLYWHEEL_BASE=/flywheel/v0
OUTPUT_DIR=$FLYWHEEL_BASE/output
CONTAINER='[flywheel/debug-generatefile]'


# Define file size (in MB)
# NOTE: Currently hardcoded as 1 GB
FILE_SIZE=1000
dd if=/dev/zero of=$OUTPUT_DIR/output.txt  bs=1M  count=$FILE_SIZE

# Get a list of the files in the output directory
outputs=`find $OUTPUT_DIR -type f -name "*"`

# If outputs exist, then go on...
if [[ -z $outputs ]]
  then
      echo "No results found in output directory... Exiting"
      exit 1
  else
      chmod -R 777 $OUTPUT_DIR
      echo -e "Wrote: `ls $OUTPUT_DIR`"
fi

exit 0

